### ISSUE TITLE
tf kms multi region key question

### ISSUE THREAD

**Issue by asaf-upstream** [cageyv/cageyv#1]
Hi Vladimir,
Hope you are well!
I saw the reply you posted here:
https://github.com/hashicorp/terraform-provider-aws/issues/19896

```
At the moment, this problem can be solved through the awscc provider:

resource "awscc_kms_key" "example_demo" {
  description            = "Key for Demo"
  key_usage              = "ENCRYPT_DECRYPT"
  key_spec               = "SYMMETRIC_DEFAULT"
  key_policy             = data.aws_iam_policy_document.example_demo.json
  pending_window_in_days = 7
  enabled                = true
  enable_key_rotation    = true
  multi_region           = true
  tags                   = module.tags.result_awscc
}

resource "aws_kms_alias" "example_demo" {
  target_key_id = awscc_kms_key.example_demo.key_id
  name          = "alias/example_demo"
}
```

And was wondering if you have tried this solution and it worked for you?
I would like to create a regional kms key with a copy of it using terraform, and I am not sure this is possible at all for the moment...
Tried to use your code, the key is being generated on us-east-1 , although I am running on us-east-2, not sure if I can specify a region..
Also, how is the copy is being made to the 2nd region? If I get the code correct, we are only adding an alias to the key, but no copy..

Would really appreciate your clarification,
Many thanks!

**Comment by cageyv** [comment]
Yes, it works for me now, but there are a number of limitations
- terraform 1.0.7+
- security risks, i.e. I can only accept ReadOnly for such resources at the moment

How to create primary key and replica key:
- use kms_key resource for primary key
- use awscc_kms_replica_key resource for replica https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/kms_replica_key

So it means we have to use different resources if we need key replication
Here you can find more info: https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-replicate.html

**Comment by cageyv** [comment]
New Resource: aws_kms_replica_key released
https://github.com/hashicorp/terraform-provider-aws/blob/v3.64.0/CHANGELOG.md
